/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthHeader: typeof import('./src/components/common/Auth/AuthHeader.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    BlogLatest: typeof import('./src/components/pages/home/BlogLatest.vue')['default']
    Breakpoints: typeof import('./src/components/common/Breakpoints.vue')['default']
    ChartLine: typeof import('./src/components/global/ChartLine.vue')['default']
    CookieAccepting: typeof import('./src/components/common/helperCommon/CookieAccepting.vue')['default']
    DarkModeSwitcher: typeof import('./src/components/common/helperCommon/DarkModeSwitcher.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    FeatursTap: typeof import('./src/components/pages/home/FeatursTap.vue')['default']
    FormattedNumber: typeof import('./src/components/global/FormattedNumber.vue')['default']
    HeaderNav: typeof import('./src/components/common/helperCommon/HeaderNav.vue')['default']
    HelpContent: typeof import('./src/components/base/Helpers/HelpContent.vue')['default']
    HelpLinks: typeof import('./src/components/pages/home/HelpLinks.vue')['default']
    HomeBanner: typeof import('./src/components/pages/home/HomeBanner.vue')['default']
    HomeFirst: typeof import('./src/components/pages/home/HomeFirst.vue')['default']
    HomeLayout: typeof import('./src/layouts/HomeLayout.vue')['default']
    HowWork: typeof import('./src/components/pages/home/HowWork.vue')['default']
    ListMarket: typeof import('./src/components/pages/home/ListMarket.vue')['default']
    Logos: typeof import('./src/components/pages/home/Logos.vue')['default']
    NotificationBase: typeof import('./src/components/base/NotificationBase.vue')['default']
    PageFooter: typeof import('./src/components/common/Home/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/common/Home/PageHeader.vue')['default']
    PageLayout: typeof import('./src/layouts/PageLayout.vue')['default']
    PairWithChart: typeof import('./src/components/global/PairWithChart.vue')['default']
    PairWithChartPrimary: typeof import('./src/components/global/PairWithChartPrimary.vue')['default']
    PriceChangePercent: typeof import('./src/components/global/PriceChangePercent.vue')['default']
    PriceColored: typeof import('./src/components/global/PriceColored.vue')['default']
    QuickMarket: typeof import('./src/components/pages/home/QuickMarket.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLogo: typeof import('./src/components/base/SiteLogo.vue')['default']
    Subscripe: typeof import('./src/components/pages/home/Subscripe.vue')['default']
    UserNav: typeof import('./src/components/common/helperCommon/UserNav.vue')['default']
  }
}
